-- TODO: Add INDEX's
CREATE DATABASE PortfolioOS;
USE PorfolioOS;

CREATE TABLE Users (
    Id SERIAL PRIMARY KEY,
    Email VARCHAR(100) NOT NULL,
    Github_Id VARCHAR(255) DEFAULT '',
    Google_Id VARCHAR(255) DEFAULT (''),
    CreateDate TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() at time zone 'UTC'),
    LastLogin TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() at time zone 'UTC'),
    Name VARCHAR(100) NULL,
    Summary TEXT NULL
)

CREATE TABLE UserIp (
    Id SERIAL PRIMARY KEY,
    UserId INT NOT NULL REFERENCES Users(Id),
    IP CIDR NOT NULL,
    Datestamp WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() at time zone 'UTC')
)

CREATE TABLE SkillSet (
    Id SERIAL PRIMARY KEY,
    UserId INT NOT NULL REFERENCES Users(Id),
    Name VARCHAR(100) NOT NULL
)

CREATE TABLE Hosts (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(50)
)

CREATE TABLE SocialLinks (
    Id SERIAL PRIMARY KEY,
    UserId INT NOT NULL REFERENCES Users(Id),
    HostId INT NOT NULL REFERENCES Hosts(Id)
)

CREATE TABLE App (
    Id SERIAL PRIMARY KEY,
    UserId INT NOT NULL REFERENCES Users(Id),
    Name VARCHAR(50) NOT NULL,
    Description TEXT DEFAULT (''),
    HtmlIndexUrl VARCHAR(500) NOT NULL,
    CreationDate TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() at time zone 'UTC'),
    LastUpdateDate TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() at time zone 'UTC')
)

CREATE TABLE AppRating (
    Id SERIAL PRIMARY KEY,
    UserId INT NOT NULL REFERENCES Users(Id),
    AppId INT NOT NULL REFERENCES App(Id),
    Datestamp WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() at time zone 'UTC'),
    IsUpVote BOOLEAN NOT NULL
)

CREATE TABLE AppDownloads (
    Id SERIAL PRIMARY KEY,
    UserId INT NOT NULL REFERENCES Users(Id),
    AppId INT NOT NULL REFERENCES App(Id)
)

CREATE TABLE FS_Local (
  Id SERIAL PRIMARY KEY,
  UserId INT NOT NULL REFERENCES Users(Id),
  DIR_desktop TEXT[] DEFAULT (ARRAY[]),
  DIR_documents TEXT[] DEFAULT (ARRAY[]),
  DIR_music TEXT[] DEFAULT (ARRAY[]),
  DIR_images TEXT[] DEFAULT (ARRAY[]),
  DIR_videos TEXT[] DEFAULT (ARRAY[]),
  DIR_shared TEXT[] DEFAULT (ARRAY[])
)
