/*
 *
 * Copyright (c) 2018 João Pedro Martins Neves (shivayl) - All Rights Reserved.
 *
 * Portfolio-OS is licensed under the GNU LGPLv3, located in the root of this
 * project, under the name "LICENSE.md".
 *
 */

// Imports for MergerJS.
//
// @import './constants'
// ignore 'https://cdnjs.cloudflare.com/ajax/libs/ajv/6.5.5/ajv.min.js'
// %import<<GH 'js-cookie/js-cookie/master/src/js.cookie.js'
// $import 'sweetalert2/dist/sweetalert2.all.min.js'
// @import './externalLibs'
// $import 'vanillatree/vanillatree.min.js'
// @import<<DIR '../../../../common/enums'
// @import<<DIR './enums/'
// @import '../../../../common/commonUtils'
// @import './utils'
// @import './domUtils'
// @import '../../../../common/models/fsItemModelBase'
// @import '../../../../common/models/fileModel'
// @import '../../../../common/models/directoryModel'
// @import '../../../../common/models/systemDirectoryModel'
// @import<<DIR './models/'
// @import './systemLibs/notifications'
// @import './systemLibs/httpClient'
// @import './systemLibs/authentication'
// @import './systemLibs/gridSystem/gridSystemTemplates'
// @import './systemLibs/gridSystem/gridSystem'
// @import './systemLibs/dragAndDrop.js'
// @import './systemLibs/windowResizer.js'
// @import './modules/fileSystem/fileSystem'
// @import './modules/taskbarManager/taskbarIcon'
// @import './modules/taskbarManager/taskbarManager'
// @import './modules/windowManager/window'
// @import './modules/windowManager/windowManager'
// @import './userApps/userAppsManager'
// @import './systemApps/systemAppsManager'
// @import './systemApps/trash/trash'
// @import './systemApps/trash/trashTemplates'
// @import './systemApps/terminal/terminalTemplates'
// @import './systemApps/terminal/terminal'
// @import './systemApps/appStore/addNewApp/addNewApp.templates'
// @import './systemApps/appStore/addNewApp/addNewApp.model'
// @import './systemApps/appStore/addNewApp/addNewApp.view'
// @import './systemApps/appStore/addNewApp/addNewApp.controller'
// @import './systemApps/appStore/appStore.templates'
// @import './systemApps/appStore/appStore.model'
// @import './systemApps/appStore/appStore.view'
// @import './systemApps/appStore/appStore.controller'
// @import './systemApps/appStore/appStore'
// @import './systemApps/profiles/myProfile/myProfile.templates'
// @import './systemApps/profiles/myProfile/myProfile.model'
// @import './systemApps/profiles/myProfile/myProfile.view'
// @import './systemApps/profiles/myProfile/myProfile.controller'
// @import './systemApps/profiles/exploreProfiles/exploreProfiles.templates'
// @import './systemApps/profiles/exploreProfiles/exploreProfiles.model'
// @import './systemApps/profiles/exploreProfiles/exploreProfiles.view'
// @import './systemApps/profiles/exploreProfiles/exploreProfiles.controller'
// @import './systemApps/profiles/userProfiles/userProfiles.templates'
// @import './systemApps/profiles/userProfiles/userProfiles.model'
// @import './systemApps/profiles/userProfiles/userProfiles.view'
// @import './systemApps/profiles/userProfiles/userProfiles.controller'
// @import './systemApps/profiles/profiles.templates'
// @import './systemApps/profiles/profiles.model'
// @import './systemApps/profiles/profiles.view'
// @import './systemApps/profiles/profiles'
// @import './systemApps/explorer/explorer.templates'
// @import './systemApps/explorer/explorer.model'
// @import './systemApps/explorer/explorer.view'
// @import './systemApps/explorer/explorer.controller'
// @import './systemApps/explorer/explorer'
// @import './userApps/shivaylCV'
// @import './modules/processManager/process'
// @import './modules/processManager/processManager'
// @import './modules/startMenuManager/startMenuApp'
// @import './modules/startMenuManager/startMenuManager'
// @import './modules/desktopManager/desktopTemplates'
// @import './modules/desktopManager/desktopIcon'
// @import './modules/desktopManager/desktopManager'
// @import './modules/contextMenu/contextMenu.templates'
// @import './modules/contextMenu/contextMenu.controller'
// @import './modules/globalEvents'
// @import './main'
//
'use strict';
